- internal/cli/app_data.go
- internal/cli/app_data_test.go
- internal/cloud/realm/app.go
- internal/cloud/realm/auth.go
- internal/cloud/realm/auth_provider.go
- internal/cloud/realm/auth_test.go
- internal/cloud/realm/client.go
- internal/cloud/realm/error.go
- internal/cloud/realm/error_test.go
- internal/cloud/realm/export.go
- internal/cloud/realm/import.go
- internal/cloud/realm/import_export_test.go
- internal/cloud/realm/realm.go
- internal/cloud/realm/user.go
- internal/cloud/realm/user_test.go
- internal/utils/api/api.go
The purpose of these import/export implementations was primarily to support testing the other Realm client actions (instead of implementing a "CreateAuthProvider" function, which the CLI's client doesn't actually need, tests should leverage importing an app with the necessary auth providers included).
Some functionality for import/export is intentionally left out here, and should/will be filled in respectively once the push and pull command tickets are picked up.
This work does however enable to use fully test the Realm client `User` methods.
**Open to ideas on naming/organization here:** Does the `realm` package make sense for all the import/export related stuff: filepath-ing, config versions, payload structs that don't necessarily line up with the API response structure, etc?
> REALMC-7632: Add import and export methods to Realm client

- internal/telemetry/service_test.go
- internal/telemetry/tracker.go
segment key is currently not populated, resulting in an awkward `12:17:34 UTC ERROR unable to connect to Segment due to missing key, CLI telemetry will be disabled` message being printed for every command. we probably shouldn't ever log this.
will get the segment key populated as a separate ticket, but this is fine for now
> REALMC-8444: Disable Segment tracking output

- internal/cli/command_factory.go
- internal/telemetry/service.go
- internal/telemetry/service_test.go
- internal/telemetry/tracker.go
the Segment library batches enqueued events until either the batch limit is hit, or a certain amount of time has elapsed (see https://segment.com/docs/connections/sources/catalog/libraries/server/go/), which was preventing events from being sent (since the program would exit before this happened).
you can create a new analytics client with a config and set the batch size to 1 according to the docs I linked agove, but I tried this and the program still exits before dispatching the events to segment. this seems to be the best way to force a flush.
I also think we need to revisit some of this soon for the case where users are blocking calls to segment and/or paranoid about tracking. I tried this with Little Snitch and it's really noisy (the Segment library uses it's own logger by default, …
> REALMC-8451: Ensure all segment events are flushed

- cmd/root.go
- internal/cli/command.go
- internal/cli/command_factory.go
- internal/commands/app/create.go
- internal/commands/app/create_inputs.go
- internal/commands/app/delete.go
- internal/commands/app/describe.go
- internal/commands/app/diff.go
- internal/commands/app/init.go
- internal/commands/app/list.go
- internal/commands/commands.go
- internal/commands/function/run.go
- internal/commands/login/command.go
- internal/commands/logout/command.go
- internal/commands/logs/list.go
- internal/commands/pull/command.go
- internal/commands/push/command.go
- internal/commands/push/command_test.go
- internal/commands/schema/models.go
- internal/commands/secrets/create.go
- internal/commands/secrets/delete.go
- internal/commands/secrets/list.go
- internal/commands/secrets/update.go
- internal/commands/user/create.go
- internal/commands/user/delete.go
- internal/commands/user/disable.go
- internal/commands/user/enable.go
- internal/commands/user/list.go
- internal/commands/user/revoke.go
- internal/commands/whoami/command.go
Updated copy: https://docs.google.com/document/d/14fBZaN47HRe3-2Pk1uSfYcCxX3Dd95wK0tprS3WE1vk/edit#
Things to look for:
Long-term thinking here: I added a `TODO` in here hopefully to start to address the issue of commands wanting to know about other commands' names, flags, etc.  Ideally we can do this in a way that prevents creating a maze of package cycles (`whoami` would end up depending on `login` and similar situations)
> REALMC-8826: Update cli help text

- internal/commands/app/delete_inputs.go
- internal/commands/app/delete_inputs_test.go
failures [here](https://spruce.mongodb.com/task/realm_cli_rhel70_test_with_cloud_patch_f83299f1742a4550a12b5f3b25a1dbf860e07372_60aeafdb5623436b0bcb854c_21_05_26_20_30_29/logs?execution=0) are unrelated to these changes, proceeding with merge
> REALMC-8645: Enable delete app using client app id

- internal/cli/user/profile.go
- internal/cli/user/profile_ext_test.go
- internal/cli/user/profile_test.go
its a messy diff, but basically:
* `git mv internal/cli/user/profile_test.go internal/cli/user/profile_ext_test.go`
* entirely new test file: `internal/cli/user/profile_test.go`
> REALMC-8944: Use default urls if not previously set in profile

- cmd/root.go
- internal/cli/command_factory.go
- internal/terminal/ui.go
i'll switch `*CommandFactory.Run` to return `error` if you still don't like this, I just wanted one last chance to defend the semantics of this code (why return `err` if you shouldn't do anything with it, as its already been consumed/reported?)
> REALMC-8824: Ensure command factory closes properly before exiting cli

- internal/cloud/realm/app.go
- internal/commands/app/create.go
- internal/commands/app/create_inputs.go
- internal/commands/app/create_inputs_test.go
- internal/commands/app/create_test.go
- internal/commands/app/new_app_inputs.go
Since we added a new field for the app creation endpoint in the `baas` PR of this ticket, we need to update the app creation request body that we send to baas from the realm-cli to match what we do in the UI.
This PR handles the above change and it adds a requirement that makes users specify a data source if they want to make a template app.
I believe prompting users for the data source that they want to use if they're requesting a template would be an improvement, but the current log should work for the time being.
> REALMC-9391: Add initial data source to app create body

- internal/cloud/realm/services.go
- internal/commands/app/create.go
- internal/commands/app/create_inputs.go
- internal/commands/app/create_inputs_test.go
- internal/commands/app/create_test.go
- internal/commands/app/new_app_inputs.go
- internal/commands/app/output.go
- Register new --template-data-source flag
- Use --template-data-source to pick template data source for app creation payload
- Add tests
> REALMC-9696: Force mongodb-atlas as template data source name

- internal/commands/app/diff.go
- internal/commands/pull/command.go
- internal/commands/push/command.go
This PR removes this error:
`panic: unable to redefine 'h' shorthand in "pull" flagset: it's already used for "include-hosting" flag`
This is caused by having the --include-hosting flag use the `-h` shorthand flag which conflicts with the -h for the `--help` command
> REALMC-9749: Remove -h shorthand flag conflict

- internal/cloud/realm/client.go
- internal/cloud/realm/templates.go
- internal/commands/app/create.go
- internal/commands/app/create_inputs.go
- internal/commands/app/create_inputs_test.go
- internal/commands/app/create_test.go
- internal/commands/app/new_app_inputs.go
- internal/commands/pull/command.go
- internal/commands/pull/command_test.go
- internal/commands/pull/inputs.go
- internal/commands/pull/inputs_test.go
- internal/utils/flags/flags.go
- internal/utils/test/mock/realm_client.go
In this PR, I've reworked how the template app creation works within the realm-cli.
We decided offline that we will start out without making a prompt for template ids and instead add the available template ids   to the help menu. We will update the help menu as we add more templates and rethink how we want to prompt for template ids once we find a good solution to REALMC-9512.
~First off, I've updated the --template flag to have a default value when it is declared but is not supplied any arguments.~
~This allows us to distinguish between the following commands:~
~1. `realm-cli app create --template=<template-id>`~
~2. `realm-cli app create --template`~
~3. `realm-cli app create`~
~1 does not prompt the user for a template because it's already supplied~
~2 prompts the user for a template~ …
> REALMC-9460: Prevent template app creation prompt from occurring automatically

- internal/commands/app/create_inputs_test.go
Ran a bunch of tests and it seems like if the default path returned on line 1238 ended in one of the letters contained in `test-app`, then that letter was “trimmed” off. 
This explains why the test was flaky: it failed only when the random hex object id ended in ‘a’ or ‘e’. 
ex. 
> If 		==> defaultPath == test-app-61803177ff64466343a31eee
> Then 	==> directoryID == 61803177ff64466343a31 (“all ‘e’s were trimmed)
Similarly for 
> If 		==> defaultPath == test-app-61803177ff64466343a31eea
> Then    ==> directoryID  == 61803177ff64466343a31 (“all ‘e’s  and ‘a’s were trimmed)
But if it ends in ‘c’, then it passes/trims correctly  because ‘c’ is not found in ‘test-app’
> If 		==> defaultPath == test-app-61802fbe11186e2e4fc7970c
> Then 	==> directoryID  == 61802fbe11186e2e4fc7970c
Solution was to …
> REALMC-10379: Fix flaky CLI test for TestFindDefaultPath

- contrib/README.md
- contrib/bump_version.bash
I think we're finally squared away with all of this now...
Output from the version bump script now:
```cmd
√ ~/go/src/github.com/10gen/realm-cli % ./contrib/bump_version.bash patch                                                                                                                                                          (REALMC-11209)realm-cli
Bumping CLI v2.3.1 to
v2.3.2
[REALMC-11209 de512ae9] REALMC-11209: Bump version to 2.3.2
1 file changed, 1 insertion(+), 1 deletion(-)
commit de512ae96a62c72dbb18325f61d78edb352a68d0 (HEAD -> REALMC-11209)
Author: Nick Makes <nick@makes.life>
Date:   Wed Dec 15 14:51:02 2021 -0500
REALMC-11209: Bump version to 2.3.2
diff --git a/package.json b/package.json
index bda1cc4a..0ccca899 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 …
```
> REALMC-11209: Specify patch/minor/major as arg into version bump script

- README.md
- internal/cli/user/auth.go
- internal/cli/user/profile.go
- internal/cloud/atlas/clusters_test.go
- internal/cloud/atlas/data_lakes_test.go
- internal/cloud/atlas/groups_test.go
- internal/cloud/atlas/status_test.go
- internal/cloud/realm/auth.go
- internal/cloud/realm/auth_test.go
- internal/cloud/realm/client.go
- internal/commands/login/command.go
- internal/commands/login/command_test.go
- internal/commands/login/inputs.go
- internal/commands/login/inputs_test.go
- internal/commands/logout/command_test.go
- internal/commands/whoami/command.go
- internal/commands/whoami/command_test.go
- internal/utils/test/mock/realm_client.go
- internal/utils/test/test.go
Mentioned this in the JIRA, but this functionality was technically missed when going from `v1` to `v2`, see: https://github.com/10gen/realm-cli/blob/support/1.3.x/auth/auth.go
Not sure how far we should go to support these use cases of "self-contained Realm instances" when testing in CI/CD environments, but Nikola reached out asking me about this so it's safe to say we have at least one real use-case for all of this
> REALMC-11391: Support local-userpass auth provider type for login

- .evg.yml
- package.json
Including one drive-by fix to remove the unused `cli_version` field from our `.evg.yml` file here
> REALMC-11637: Bump version to 2.3.4

- internal/cli/command_factory.go
- internal/cloud/realm/auth.go
- internal/cloud/realm/client.go
[bug fix]: fixes auth loop bug that occurs when running cli commands that require client authentication (e.g. apps list, or apps create). JIRA ticket [here](https://jira.mongodb.org/browse/REALMC-10889)
Note: Currently returns only "invalid session", but a Suggestion bug is being addressed on [11700](https://github.com/10gen/realm-cli/pull/251)
> REALMC-10889: Add truthy PreventAuth flag to refreshAuth request options

- .evg.yml
- README.md
- e2e/cli_test.go
- internal/cli/command_factory.go
- internal/cli/command_factory_test.go
- internal/cli/version.go
- internal/cli/version_test.go
Noticed this when testing out `npx` this morning:
```cmd
% npx mongodb-realm-cli whoami
New version (v2.3.5) of CLI available: https://s3.amazonaws.com/realm-clis/realm_cli_rhel70_c61061f62167023c81195fd09ba42bd5cdfade6e_22_03_02_20_09_42/macos-amd64/realm-cli
Note: This is the only time this alert will display today
To install
npm install -g mongodb-realm-cli@v2.3.5
curl -o ./mongodb-realm-cli https://s3.amazonaws.com/realm-clis/realm_cli_rhel70_c61061f62167023c81195fd09ba42bd5cdfade6e_22_03_02_20_09_42/macos-amd64/realm-cli && chmod +x ./mongodb-realm-cli
Currently logged in user: aoicacni (********-****-****-****-3e0f6e5e9dca)
```
I'm changing the `curl` output to reference the executable name `realm-cli`, rather than the (more verbose) npm package name `mongodb-realm-cli`... which …
> REALMC-12080: Change name of executable in outdated version warning to realm-cli

- .evg.yml
The `test_with_cloud` task has been failing because the server requires go 1.17.
> REALMC-12352: upgrade go to 1.17 for test_with_cloud task

- go.mod
- internal/commands/app/init_inputs_test.go
- internal/commands/push/command.go
- internal/commands/push/command_test.go
- internal/commands/push/inputs_test.go
- internal/local/app.go
- internal/local/app_test.go
- internal/local/testdata/20180301/mismatch_version/stitch.json
- internal/local/testdata/20200603/mismatch_version/config.json
- internal/local/testdata/20210101/mismatch_version/realm_config.json
[Ticket here](https://jira.mongodb.org/browse/REALMC-11800)
I added one test to verify that the `realm_config` was being created properly when running the command. I couldn't figure out a clean way to teardown the test, though, since the push handler tests all use the existing `testdata/project` directory for the environment.
Mocking out the `createNewApp` method might be a nice way to do this, since we could just verify that the method's being called with the right params, but it didn't seem like that's something we support in this repo.
> REALMC-11800: Use root directory to create app on nested push command

- .gitignore
- internal/cloud/atlas/client.go
- internal/cloud/atlas/serverless_instances.go
- internal/cloud/atlas/serverless_instances_test.go
- internal/commands/app/create.go
- internal/commands/app/create_inputs.go
- internal/commands/app/create_inputs_test.go
- internal/commands/app/create_test.go
- internal/commands/app/output.go
- internal/utils/test/mock/atlas_client.go
- internal/utils/test/test.go
https://jira.mongodb.org/browse/REALMC-11567
Adding `--serverless-instance` and `--serverless-instance-service-name` flags to `realm-cli apps create`
> REALMC-11567: Allow users to link serverless instances on app creation

- internal/local/app_test.go
- internal/local/data.go
- internal/local/structure.go
- internal/local/structure_test.go
- internal/local/structure_v2.go
- internal/local/structure_v2_test.go
- internal/local/testdata/data_sources/data_sources/mongodb-atlas/default_rule.json
- internal/local/testdata/full_project/services/mdbSvc/config.json
- internal/local/testdata/full_project/services/mdbSvc/default_rule.json
- internal/local/testdata/full_project/services/mdbSvc/rules/foo.bar.json
- Add the Default Rule to the exported app structure for App Structure V1 and V2
- Write and parse the default rule to/from the Data Sources directory for App Structure V2
- Write and parse the default rule to/from the Services directory for App Structure V1
> REALMC-12113: Add DefaultRule to exported app structure

- README.md
[Ticket](https://jira.mongodb.org/browse/REALMC-12450)
This one isn't blocked by the stitch support lib ticket but we can wait until the [baas PR](https://github.com/10gen/baas/pull/6261) is merged if we want to close out the ticket all at once.
> REALMC-12450: Update onboarding docs for M1 users

- internal/cli/inputs.go
- internal/cli/inputs_test.go
- internal/cloud/atlas/client.go
- internal/cloud/atlas/clusters.go
- internal/cloud/atlas/data_lakes.go
- internal/cloud/atlas/groups.go
- internal/cloud/atlas/groups_test.go
- internal/cloud/atlas/serverless_instances.go
- internal/cloud/atlas/status.go
- internal/commands/app/create_test.go
- internal/commands/pull/inputs_test.go
- internal/commands/push/command_test.go
- internal/utils/test/mock/atlas_client.go
In terms of testing, it looks like we only have access to 1 group. Is it possible to add more groups? at least 1 so we can pass in a `itemsPerPage = 1` query param to force the fetch for more groups: https://github.com/10gen/realm-cli/blob/3795c0740d25d61bed4de823807e7351fcd06bbf/internal/utils/test/test.go#L39
ex
for testing manually, I passed `api.RequestOptions{Query: map[string]string{"itemsPerPage":"1"}}` for profiles in which I had multiple groups and 'printed' the 'next link' to the terminal
```
jamie.anderson@M-C02F15DGMD6M mongodb % ./realm-cli-next --profile dev pull
NEXT LINK: &{https://cloud-dev.mongodb.com/api/public/v1.0/groups?itemsPerPage=1&pageNum=2 next}
NEXT LINK: &{https://cloud-dev.mongodb.com/api/public/v1.0/groups?itemsPerPage=1&pageNum=3 next}
? Atlas Project  [Use …
```
> REALMC-13094: fetch all available groups from Atlas Public API

- internal/cloud/realm/dependencies_test.go
- internal/cloud/realm/import_export_test.go
Should go in after 10gen/baas#6766 gets merged, the tests will fail in the meantime
> BAAS-14012: Skip setting Data API Config run_as_system=true in import/export round trip tests

- internal/cloud/realm/app.go
This PR adds `device-sync` to the list of default product types for push/pull support
> BAAS-23774: Add device-sync product type to realm-cli
