10gen/realm-cli

testdata/full_app/graphql/config.json
utils/utils.go
utils/utils_test.go

- Added tracking of the graphql config when unmarshalling graphql directory

REALMC-5975: Track graphql config during app importexport

---

utils/utils.go
utils/utils_test.go

evergreen wasn't set up properly to run the lint task on PRs (my fault), should be good now

REALMC-6522: Fixup utils and utils_test linting

---

commands/diff.go

[JIRA](https://jira.mongodb.org/browse/REALMC-7207)

REALMC-7207: Add support for the strategy flag when using the diff command

---

internal/cloud/realm/import_export_test.go
internal/local/data.go
internal/local/structure_v1.go
internal/local/structure_v2.go

REALMC-7998: Include auth and data_sources to new import request

---

internal/cli/inputs.go
internal/cloud/realm/app.go
internal/cloud/realm/import_export_test.go
internal/commands/app/list.go
internal/commands/pull/inputs.go
internal/commands/push/inputs.go
internal/local/app.go
internal/local/app_test.go
internal/local/data.go
internal/local/structure.go
internal/local/structure_v1.go
internal/local/structure_v2.go
internal/local/testdata/full_project/graphql/custom_resolvers/query_result.json

REALMC-8006: Include http_endpoints to new import request

---

internal/cloud/realm/import_export_test.go
internal/local/data.go
internal/local/structure.go
internal/local/structure_v2.go
internal/local/structure_v2_test.go
internal/local/testdata/functions/functions/config.json
internal/local/testdata/functions/functions/eggcorn.js
internal/local/testdata/functions/functions/foo/bar.js
internal/local/testdata/functions/realm_config.json

to be merged after [`REALMC-8296`](https://github.com/10gen/baas/pull/3865)

REALMC-7989: Include functions in new import request

---

install.js

Permit install on darwin arm64.

---

internal/cloud/realm/dependencies_test.go
internal/commands/pull/command.go
internal/commands/pull/command_test.go
internal/local/hosting.go

* 'rw' should be sufficient here, don't need executable

REALMC-8432: Set correct file permissions for static files

---

.evg.yml

releasing a new 1.3.x to get recently merged segment tracking code in

REALMC-8727: Bump version to 1.3.3

---

internal/cloud/realm/app.go
internal/cloud/realm/realm.go
internal/commands/app/create.go
internal/commands/app/create_inputs.go
internal/commands/app/create_inputs_test.go
internal/commands/app/init.go
internal/commands/app/init_inputs_test.go
internal/commands/app/new_app_inputs.go
internal/commands/push/command.go
internal/commands/push/command_test.go
internal/local/app.go
internal/local/app_test.go
internal/local/data.go
internal/local/structure_v1.go
internal/local/structure_v2.go

REALMC-9018: Add environment to create app steps

---

internal/commands/app/create_test.go
internal/commands/app/new_app_inputs.go

whoops, wasn't paying attention when I commented this out in the last PR... fail.

REALMC-8260: Fix up disabling of template selection

---

internal/commands/app/create.go
internal/commands/app/create_test.go
internal/commands/app/output.go
internal/commands/user/create.go
internal/commands/user/create_test.go
internal/commands/user/output.go

~Leaving this as a draft/wip for now as we wait for #166 to be merged first~

REALMC-8262: Use json document display instead of table for created resources

---

internal/commands/app/create.go
internal/commands/app/create_test.go
internal/commands/app/new_app_inputs.go

merging this into `support/v2.0.x` (i.e. `beta.7`)

REALMC-9541: Fix beta.7 template handling

---

internal/commands/pull/command.go
internal/commands/pull/command_test.go
internal/commands/pull/inputs.go
internal/commands/pull/inputs_test.go

- REALMC-9452: Write client templates to file system in sorted order

REALMC-9452: Write template clients to file system in sorted order

---

internal/cloud/realm/access_list.go

Corresponding backend change: https://github.com/10gen/baas/pull/4658

REALMC-9689: change UPDATE to PATCH in Access List

---

internal/cloud/realm/app_description.go
internal/cloud/realm/app_ext_test.go
internal/commands/app/describe_test.go

Implementation includes:
1. Add logforwardersummary to app_description.go
2. Add unit test for it
Question:
Integration is failing cause I think we don't have baas side change merged yet. I ran the test on my local and it works fine. Should we not merge this change until baas change is merged?

REALMC-10273: Add logforwarder to AppDescription

---

internal/commands/app/create.go
internal/commands/function/run.go
internal/commands/function/run_test.go
internal/commands/pull/command.go
internal/commands/push/command.go
internal/commands/push/command_test.go
internal/terminal/spinner.go
internal/terminal/ui.go

Related to: https://github.com/10gen/realm-cli/issues/204

REALMC-10284: Disable spinners when minimal UI is requested

---

internal/commands/login/command.go

Addresses issue specified in #247

REALMC-11629: Set correct default on login auth-type flag

---

go.mod
go.sum
internal/terminal/ui.go

Updated the survey pkg: https://github.com/alphayan/survey to version [v2.2.3](https://github.com/AlecAivazis/survey/releases/tag/v2.2.3)
Now the default value is shown when selected.

REALMC-9026: display the default value for input prompt when selected

---

internal/cloud/realm/import_export_test.go

REALMC-11804: revert temporary fix for import/export test

---

e2e/cli_test.go
internal/local/structure_v2.go
internal/local/structure_v2_test.go

JIRA: https://jira.mongodb.org/browse/REALMC-12163

REALMC-12163: Avoid creating empty schema/relationships when importing a directory with just a rule

---

README.md
e2e/cli_test.go
internal/cloud/realm/user_ext_test.go
internal/commands/login/command.go
internal/commands/login/inputs.go
internal/commands/login/inputs_test.go
internal/commands/logout/command.go
internal/commands/user/create.go
internal/commands/user/create_test.go
internal/commands/whoami/command.go

depends on https://github.com/10gen/realm-cli/pull/300

BAAS-14085: add 'browser' flag for cli login

---

cmd/root.go
go.mod
internal/cli/user/auth.go
internal/cli/user/profile.go
internal/commands/commands.go
internal/commands/login/command.go
internal/commands/profile/list.go
internal/commands/profile/list_test.go
internal/commands/whoami/command.go
internal/local/environment.go
internal/local/environment_test.go

```
jamie.anderson@M-C02F15DGMD6M mongodb % ./realm-cli-next profiles list
Found 6 profiles
default.yaml
dev.yaml
local.yaml
local_dev.yaml
prod.yaml
qa.yaml
```

BAAS-14096: add hidden 'profiles list' command
